//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Model;
    
    public partial class GoSecEntities : DbContext
    {
        public GoSecEntities()
            : base("name=GoSecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoginPsw> LoginPsw { get; set; }
        public virtual DbSet<LoginSchoolPsw> LoginSchoolPsw { get; set; }
        public virtual DbSet<StudentInfo> StudentInfo { get; set; }
    }
}
